# Generated by Django 3.1.2 on 2020-11-21 10:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 11, 21, 10, 41, 4, 477985, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='offered_price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2020, 11, 21, 10, 41, 8, 71201, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
