# Generated by Django 3.1.2 on 2020-11-25 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20201121_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='offered_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
