# Generated by Django 3.1.2 on 2020-11-08 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20201106_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('deleted_why', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('deleted_why', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListingType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('deleted_why', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('zip_code', models.CharField(max_length=10)),
                ('street_address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('sqft_area', models.IntegerField(null=True)),
                ('bedrooms', models.IntegerField()),
                ('bathroom', models.IntegerField()),
                ('flooring', models.CharField(max_length=100, null=True)),
                ('year_built', models.IntegerField()),
                ('kitchen', models.CharField(max_length=100, null=True)),
                ('laundry', models.CharField(max_length=100, null=True)),
                ('parking_type', models.CharField(max_length=100, null=True)),
                ('air_conditioner', models.CharField(max_length=100, null=True)),
                ('heater', models.CharField(max_length=100, null=True)),
                ('available_date', models.DateTimeField(null=True)),
                ('lease_term', models.IntegerField(null=True)),
                ('security_deposit', models.IntegerField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('deleted_why', models.TextField(null=True)),
                ('home_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home_listing.homestatus')),
                ('home_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home_listing.hometype')),
                ('listed_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.user')),
                ('listing_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home_listing.listingtype')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField()),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home_listing.listing')),
            ],
        ),
        migrations.CreateModel(
            name='HomeSchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('schedule_datetime', models.DateTimeField()),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('deleted_why', models.TextField(null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home_listing.listing')),
                ('scheduled_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.user')),
            ],
        ),
    ]
