# Generated by Django 3.1.2 on 2020-11-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_listing', '0002_auto_20201118_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='air_conditioner',
            field=models.BooleanField(default=False),
        ),
    ]
