# Generated by Django 3.1.2 on 2020-11-24 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20201122_1304'),
        ('home_listing', '0003_auto_20201118_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeschedule',
            name='schedule_datetime',
        ),
        migrations.AddField(
            model_name='homeschedule',
            name='schedule_visits_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homeschedule',
            name='schedule_visits_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OpenHouse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('open_house_date', models.DateField(blank=True, null=True)),
                ('open_house_start_time', models.TimeField(blank=True, null=True)),
                ('open_house_end_time', models.TimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_why', models.TextField(blank=True, null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home_listing.listing')),
                ('scheduled_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.user')),
            ],
        ),
    ]
