# Generated by Django 3.1.2 on 2020-11-24 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_listing', '0004_auto_20201124_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openhouse',
            name='scheduled_by',
        ),
    ]
