# Generated by Django 3.1.2 on 2020-11-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_listing', '0006_remove_openhouse_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlooringType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_why', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_why', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='listing',
            name='flooring',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='parking_type',
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='year_built',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
