# Generated by Django 3.1.2 on 2020-11-25 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_listing', '0007_auto_20201125_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeschedule',
            name='description',
        ),
        migrations.AddField(
            model_name='listing',
            name='floor_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home_listing.flooringtype'),
        ),
        migrations.AddField(
            model_name='listing',
            name='parking_space_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home_listing.parkingtype'),
        ),
    ]
