# Generated by Django 3.1.2 on 2020-11-30 01:42

from django.db import migrations, models


def convert_date_time_date(apps, schema_editor):
    Listing = apps.get_model('home_listing', 'Listing')

    for listing in Listing.objects.all():
        if listing.available_date_time:
            listing.available_date = listing.available_date_time.date()
            listing.save()


class Migration(migrations.Migration):

    dependencies = [
        ('home_listing', '0010_auto_20201130_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='available_date',
            field=models.DateField(blank=True, null=True),
        ),

        migrations.RunPython(convert_date_time_date),
    ]
