# Generated by Django 3.1.2 on 2020-11-18 11:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201106_2248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='created_datetime',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='userstatus',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='usertype',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='useradditionalinfo',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='deleted_why',
        ),
        migrations.AddField(
            model_name='role',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='useradditionalinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='useradditionalinfo',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='useradditionalinfo',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useradditionalinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='userstatus',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userstatus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='usertype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.usertype'),
        ),
        migrations.AlterField(
            model_name='useradditionalinfo',
            name='annual_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='useradditionalinfo',
            name='credit_score',
            field=models.IntegerField(default=700),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
