# Generated by Django 3.1.2 on 2020-11-21 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201121_0111'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAdditionalInfoLog',
        ),
        migrations.DeleteModel(
            name='UserLog',
        ),
    ]
