# Generated by Django 3.1.2 on 2020-11-21 10:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201121_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 11, 21, 10, 4, 39, 789531, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='role',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2020, 11, 21, 10, 4, 41, 390065, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 11, 21, 10, 4, 42, 966518, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2020, 11, 21, 10, 4, 44, 502145, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useradditionalinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 11, 21, 10, 4, 46, 86799, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useradditionalinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2020, 11, 21, 10, 4, 47, 750696, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 11, 21, 10, 4, 49, 278189, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2020, 11, 21, 10, 4, 50, 838484, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usertype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 11, 21, 10, 4, 52, 438414, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usertype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2020, 11, 21, 10, 4, 54, 38185, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
