# Generated by Django 3.1.2 on 2020-11-21 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201121_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.userstatus'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='core.usertype'),
        ),
        migrations.AlterField(
            model_name='useradditionalinfo',
            name='annual_salary',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
