# Generated by Django 3.1.2 on 2020-11-22 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201121_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default='user', on_delete=django.db.models.deletion.CASCADE, to='core.role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_status',
            field=models.ForeignKey(default='pending', on_delete=django.db.models.deletion.CASCADE, to='core.userstatus'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='core.usertype'),
        ),
    ]
