# Generated by Django 3.1.2 on 2020-11-22 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201121_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='core.role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_status',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='core.userstatus'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='core.usertype'),
        ),
    ]
