# Generated by Django 3.1.2 on 2020-11-25 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20201124_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='deleted_why',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_why',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useradditionalinfo',
            name='deleted_why',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userstatus',
            name='deleted_why',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertype',
            name='deleted_why',
            field=models.TextField(blank=True, null=True),
        ),
    ]
